apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-bad-image
  annotations:
    vm.kubevirt.io/description: "VM with bad image for testing"
    vm.kubevirt.io/owner: "test-team"
    vm.kubevirt.io/environment: "dev"
spec:
  runStrategy: Halted
  template:
    metadata:
      labels:
        kubevirt.io/domain: vm-bad-image
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
          interfaces:
          - name: default
            masquerade: {}
        resources:
          requests:
            cpu: "100m"
            memory: "128M"
          limits:
            cpu: "200m"
            memory: "256M"
      networks:
      - name: default
        pod: {}
  volumes:
    - name: containerdisk
      containerDisk:
        image: "docker.io/nginx:latest"
