apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-good
  annotations:
    vm.kubevirt.io/description: "A properly configured VM that passes all policy validations"
    vm.kubevirt.io/owner: "platform-team"
    vm.kubevirt.io/environment: "dev"
spec:
  runStrategy: Halted
  template:
    metadata:
      labels:
        kubevirt.io/domain: vm-good
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: default
            masquerade: {}
        resources:
          requests:
            cpu: "100m"
            memory: "128M"
      networks:
      - name: default
        pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/kubevirt/cirros-container-disk-demo
        - name: cloudinitdisk
          cloudInitNoCloud:
            userDataBase64: SGkuXG4=
