apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-positive-test
  annotations:
    vm.kubevirt.io/description: "Positive test VM for policy validation"
    vm.kubevirt.io/owner: "platform-team"
    vm.kubevirt.io/environment: "dev"
spec:
  runStrategy: Halted
  template:
    metadata:
      labels:
        kubevirt.io/domain: vm-positive-test
    spec:
      securityContext:
        runAsNonRoot: true
        readOnlyRootFilesystem: true
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: default
            masquerade: {}
        resources:
          requests:
            cpu: "100m"
            memory: "128M"
          limits:
            cpu: "200m"
            memory: "256M"
      networks:
      - name: default
        pod: {}
  volumes:
    - name: containerdisk
      containerDisk:
        image: quay.io/kubevirt/cirros-container-disk-demo
    - name: cloudinitdisk
      cloudInitNoCloud:
        userDataBase64: SGkuXG4=
